name: ci

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 16, 18 ]

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm test

    - name: npm audit
      run: npm audit --json > npm-audit-results.json
      continue-on-error: true

    - name: upload audit report
      uses: actions/upload-artifact@v4
      with:
        name: npm-audit-results
        path: npm-audit-results.json
